################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch : true
    network: proxy
################################################################
# Traefik Logging
################################################################
log:
  level: DEBUG
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"







